#!/bin/bash

echo "Building VCT datastore..."
docker build -t vct_datastore vct_datastore/


echo "Building VCT database..."
docker build -t vct_postgres vct_postgres/


echo "Building VCT controller..."
docker build -t vct_controller_dummy vct_controller_dummy/
